from typing import Optional, List
from pydantic import BaseModel, Field

class CaseBase(BaseModel):
    eventid: Optional[int] = None
    iyear: Optional[int] = Field(None, description="Year when the incident occurred")
    imonth: Optional[int] = Field(None, description="Month when the incident occurred")
    iday: Optional[int] = Field(None, description="Day when the incident occurred")
    approxdate: Optional[str] = Field(None, description="Approximate date if exact date unknown")
    extended: Optional[int] = Field(None, description="Duration of incident (1=24+ hours)")
    resolution: Optional[str] = Field(None, description="Date incident was resolved")
    country: Optional[int] = Field(None, description="Country code")
    country_txt: Optional[str] = Field(None, description="Country name")
    region: Optional[int] = Field(None, description="Region code")
    region_txt: Optional[str] = Field(None, description="Region name")
    provstate: Optional[str] = Field(None, description="Province/state/administrative region")
    city: Optional[str] = Field(None, description="City name")
    latitude: Optional[float] = Field(None, description="Latitude of incident")
    longitude: Optional[float] = Field(None, description="Longitude of incident")
    specificity: Optional[int] = Field(None, description="Specificity of incident location")
    vicinity: Optional[int] = Field(None, description="1=Incident in the immediate vicinity of city")
    location: Optional[str] = Field(None, description="Specific location description")
    summary: Optional[str] = Field(None, description="Brief description of the incident")
    crit1: Optional[int] = Field(None, description="Criterion 1 satisfied")
    crit2: Optional[int] = Field(None, description="Criterion 2 satisfied")
    crit3: Optional[int] = Field(None, description="Criterion 3 satisfied")
    doubtterr: Optional[int] = Field(None, description="Doubt terrorism proper")
    alternative: Optional[int] = Field(None, description="Alternative designation")
    alternative_txt: Optional[str] = Field(None, description="Alternative designation text")
    multiple: Optional[int] = Field(None, description="1=Part of multiple incident")
    success: Optional[int] = Field(None, description="1=Attack was successful")
    suicide: Optional[int] = Field(None, description="1=Suicide attack")
    attacktype1: Optional[int] = Field(None, description="General method of attack")
    attacktype1_txt: Optional[str] = Field(None, description="General method of attack text")
    attacktype2: Optional[int] = Field(None, description="Secondary method of attack")
    attacktype2_txt: Optional[str] = Field(None, description="Secondary method of attack text")
    attacktype3: Optional[int] = Field(None, description="Tertiary method of attack")
    attacktype3_txt: Optional[str] = Field(None, description="Tertiary method of attack text")
    targtype1: Optional[int] = Field(None, description="General type of target/victim")
    targtype1_txt: Optional[str] = Field(None, description="General type of target/victim text")
    targsubtype1: Optional[int] = Field(None, description="More specific target category")
    targsubtype1_txt: Optional[str] = Field(None, description="More specific target category text")
    corp1: Optional[str] = Field(None, description="Name of corporate entity or government agency")
    target1: Optional[str] = Field(None, description="Specific target/victim")
    natlty1: Optional[int] = Field(None, description="Nationality of target/victim")
    natlty1_txt: Optional[str] = Field(None, description="Nationality of target/victim text")
    targtype2: Optional[int] = Field(None, description="General type of secondary target/victim")
    targtype2_txt: Optional[str] = Field(None, description="General type of secondary target/victim text")
    targsubtype2: Optional[int] = Field(None, description="More specific secondary target category")
    targsubtype2_txt: Optional[str] = Field(None, description="More specific secondary target category text")
    corp2: Optional[str] = Field(None, description="Name of secondary corporate entity or government agency")
    target2: Optional[str] = Field(None, description="Specific secondary target/victim")
    natlty2: Optional[int] = Field(None, description="Nationality of secondary target/victim")
    natlty2_txt: Optional[str] = Field(None, description="Nationality of secondary target/victim text")
    targtype3: Optional[int] = Field(None, description="General type of tertiary target/victim")
    targtype3_txt: Optional[str] = Field(None, description="General type of tertiary target/victim text")
    targsubtype3: Optional[int] = Field(None, description="More specific tertiary target category")
    targsubtype3_txt: Optional[str] = Field(None, description="More specific tertiary target category text")
    corp3: Optional[str] = Field(None, description="Name of tertiary corporate entity or government agency")
    target3: Optional[str] = Field(None, description="Specific tertiary target/victim")
    natlty3: Optional[int] = Field(None, description="Nationality of tertiary target/victim")
    natlty3_txt: Optional[str] = Field(None, description="Nationality of tertiary target/victim text")
    gname: Optional[str] = Field(None, description="Name of group claiming responsibility")
    gsubname: Optional[str] = Field(None, description="Subgroup name")
    gname2: Optional[str] = Field(None, description="Name of secondary group claiming responsibility")
    gsubname2: Optional[str] = Field(None, description="Secondary subgroup name")
    gname3: Optional[str] = Field(None, description="Name of tertiary group claiming responsibility")
    gsubname3: Optional[str] = Field(None, description="Tertiary subgroup name")
    motive: Optional[str] = Field(None, description="Motive for the attack")
    guncertain1: Optional[int] = Field(None, description="1=Uncertainty about perpetrator group identity")
    guncertain2: Optional[int] = Field(None, description="1=Uncertainty about secondary perpetrator group identity")
    guncertain3: Optional[int] = Field(None, description="1=Uncertainty about tertiary perpetrator group identity")
    individual: Optional[int] = Field(None, description="1=Perpetrator was an unaffiliated individual(s)")
    nperps: Optional[int] = Field(None, description="Number of perpetrators")
    nperpcap: Optional[int] = Field(None, description="Number of perpetrators captured")
    claimed: Optional[int] = Field(None, description="1=Responsibility was claimed")
    claimmode: Optional[int] = Field(None, description="How responsibility was claimed")
    claimmode_txt: Optional[str] = Field(None, description="How responsibility was claimed text")
    claim2: Optional[int] = Field(None, description="Secondary claim of responsibility")
    claimmode2: Optional[int] = Field(None, description="How secondary responsibility was claimed")
    claimmode2_txt: Optional[str] = Field(None, description="How secondary responsibility was claimed text")
    claim3: Optional[int] = Field(None, description="Tertiary claim of responsibility")
    claimmode3: Optional[int] = Field(None, description="How tertiary responsibility was claimed")
    claimmode3_txt: Optional[str] = Field(None, description="How tertiary responsibility was claimed text")
    compclaim: Optional[int] = Field(None, description="1=Competing claims of responsibility")
    weaptype1: Optional[int] = Field(None, description="General type of weapon used")
    weaptype1_txt: Optional[str] = Field(None, description="General type of weapon used text")
    weapsubtype1: Optional[int] = Field(None, description="More specific weapon type")
    weapsubtype1_txt: Optional[str] = Field(None, description="More specific weapon type text")
    weaptype2: Optional[int] = Field(None, description="General type of secondary weapon used")
    weaptype2_txt: Optional[str] = Field(None, description="General type of secondary weapon used text")
    weapsubtype2: Optional[int] = Field(None, description="More specific secondary weapon type")
    weapsubtype2_txt: Optional[str] = Field(None, description="More specific secondary weapon type text")
    weaptype3: Optional[int] = Field(None, description="General type of tertiary weapon used")
    weaptype3_txt: Optional[str] = Field(None, description="General type of tertiary weapon used text")
    weapsubtype3: Optional[int] = Field(None, description="More specific tertiary weapon type")
    weapsubtype3_txt: Optional[str] = Field(None, description="More specific tertiary weapon type text")
    weaptype4: Optional[int] = Field(None, description="General type of quaternary weapon used")
    weaptype4_txt: Optional[str] = Field(None, description="General type of quaternary weapon used text")
    weapsubtype4: Optional[int] = Field(None, description="More specific quaternary weapon type")
    weapsubtype4_txt: Optional[str] = Field(None, description="More specific quaternary weapon type text")
    weapdetail: Optional[str] = Field(None, description="Additional details about weapon(s) used")
    nkill: Optional[float] = Field(None, description="Number of confirmed fatalities")
    nkillus: Optional[float] = Field(None, description="Number of US citizens killed")
    nkillter: Optional[float] = Field(None, description="Number of perpetrator fatalities")
    nwound: Optional[float] = Field(None, description="Number of confirmed non-fatal injuries")
    nwoundus: Optional[float] = Field(None, description="Number of US citizens injured")
    nwoundte: Optional[float] = Field(None, description="Number of perpetrators injured")
    property: Optional[int] = Field(None, description="1=Property damage")
    propextent: Optional[int] = Field(None, description="Extent of property damage")
    propextent_txt: Optional[str] = Field(None, description="Extent of property damage text")
    propvalue: Optional[float] = Field(None, description="Value of property damage (in USD)")
    propcomment: Optional[str] = Field(None, description="Comment on property damage")
    ishostkid: Optional[int] = Field(None, description="1=Incident involved a hostage or kidnapping")
    nhostkid: Optional[int] = Field(None, description="Total number of hostages or kidnapping victims")
    nhostkidus: Optional[int] = Field(None, description="Number of US hostages or kidnapping victims")
    nhours: Optional[int] = Field(None, description="Hours of kidnapping/hostage incident")
    ndays: Optional[int] = Field(None, description="Days of kidnapping/hostage incident")
    divert: Optional[str] = Field(None, description="Location where hijacked vehicle was diverted to")
    kidhijcountry: Optional[str] = Field(None, description="Country of kidnap/hijack resolution")
    ransom: Optional[int] = Field(None, description="1=Ransom demanded")
    ransomamt: Optional[float] = Field(None, description="Amount of ransom demanded")
    ransomamtus: Optional[float] = Field(None, description="Amount of ransom demanded in USD")
    ransompaid: Optional[float] = Field(None, description="Amount of ransom paid")
    ransompaidus: Optional[float] = Field(None, description="Amount of ransom paid in USD")
    ransomnote: Optional[str] = Field(None, description="Text of ransom note")
    hostkidoutcome: Optional[int] = Field(None, description="Outcome of hostage/kidnapping incident")
    hostkidoutcome_txt: Optional[str] = Field(None, description="Outcome of hostage/kidnapping incident text")
    nreleased: Optional[int] = Field(None, description="Number of hostages released")
    addnotes: Optional[str] = Field(None, description="Additional notes")
    scite1: Optional[str] = Field(None, description="First source citation")
    scite2: Optional[str] = Field(None, description="Second source citation")
    scite3: Optional[str] = Field(None, description="Third source citation")
    dbsource: Optional[str] = Field(None, description="Source of the data")
    INT_LOG: Optional[int] = Field(None, description="International logistical attack")
    INT_IDEO: Optional[int] = Field(None, description="International ideological attack")
    INT_MISC: Optional[int] = Field(None, description="International miscellaneous attack")
    INT_ANY: Optional[int] = Field(None, description="Any international attack")
    related: Optional[str] = Field(None, description="Related incidents")

class CaseSchema(BaseModel):
    status_code: int
    status: str
    message: str
    page: int
    total_pages: int
    data: List[CaseBase]

    class Config:
        from_attributes = True