from sqlalchemy  import Column, Integer, String, Text, Float, BigInteger
from config.database import Base

class Case(Base):
    __tablename__ = "case"

    eventid = Column(BigInteger,primary_key=True, index=True, nullable=False)
    iyear = Column(Integer, index=True, nullable=True)
    imonth = Column(Integer, index=True, nullable=True)
    iday = Column(Integer, index=True, nullable=True)
    approxdate = Column(String(256), nullable=True)
    extended = Column(Integer, nullable=True)
    resolution = Column(String(256), nullable=True)
    country = Column(Integer, index=True, nullable=True)
    country_txt = Column(String(256), index=True, nullable=True)
    region = Column(Integer, index=True, nullable=True)
    region_txt = Column(String(256), index=True, nullable=True)
    provstate = Column(String(256), index=True, nullable=True)
    city = Column(String(256), index=True, nullable=True)
    latitude = Column(Float, nullable=True)
    longitude = Column(Float, nullable=True)
    specificity = Column(Integer, nullable=True)
    vicinity = Column(Integer, nullable=True)
    location = Column(Text, nullable=True)
    summary = Column(Text, nullable=True)
    crit1 = Column(Integer, nullable=True)
    crit2 = Column(Integer, nullable=True)
    crit3 = Column(Integer, nullable=True)
    doubtterr = Column(Integer, index=True, nullable=True)
    alternative = Column(Integer, nullable=True)
    alternative_txt = Column(String(256), nullable=True)
    multiple = Column(Integer, index=True, nullable=True)
    success = Column(Integer, index=True, nullable=True)
    suicide = Column(Integer, index=True, nullable=True)
    attacktype1 = Column(Integer, index=True, nullable=True)
    attacktype1_txt = Column(String(256), index=True, nullable=True)
    attacktype2 = Column(Integer, nullable=True)
    attacktype2_txt = Column(String(256), nullable=True)
    attacktype3 = Column(Integer, nullable=True)
    attacktype3_txt = Column(String(256), nullable=True)
    targtype1 = Column(Integer, index=True, nullable=True)
    targtype1_txt = Column(String(256), index=True, nullable=True)
    targsubtype1 = Column(Integer, index=True, nullable=True)
    targsubtype1_txt = Column(String(256), nullable=True)
    corp1 = Column(String(256), index=True, nullable=True)
    target1 = Column(Text, nullable=True)
    natlty1 = Column(Integer, index=True, nullable=True)
    natlty1_txt = Column(String(256), index=True, nullable=True)
    targtype2 = Column(Integer, nullable=True)
    targtype2_txt = Column(String(256), nullable=True)
    targsubtype2 = Column(Integer, nullable=True)
    targsubtype2_txt = Column(String(256), nullable=True)
    corp2 = Column(String(256), nullable=True)
    target2 = Column(Text, nullable=True)
    natlty2 = Column(Integer, nullable=True)
    natlty2_txt = Column(String(256), nullable=True)
    targtype3 = Column(Integer, nullable=True)
    targtype3_txt = Column(String(256), nullable=True)
    targsubtype3 = Column(Integer, nullable=True)
    targsubtype3_txt = Column(String(256), nullable=True)
    corp3 = Column(String(256), nullable=True)
    target3 = Column(Text, nullable=True)
    natlty3 = Column(Integer, nullable=True)
    natlty3_txt = Column(String(256), nullable=True)
    gname = Column(String(256), index=True, nullable=True)
    gsubname = Column(String(256), nullable=True)
    gname2 = Column(String(256), nullable=True)
    gsubname2 = Column(String(256), nullable=True)
    gname3 = Column(String(256), nullable=True)
    gsubname3 = Column(String(256), nullable=True)
    motive = Column(Text, nullable=True)
    guncertain1 = Column(Integer, nullable=True)
    guncertain2 = Column(Integer, nullable=True)
    guncertain3 = Column(Integer, nullable=True)
    individual = Column(Integer, index=True, nullable=True)
    nperps = Column(Integer, nullable=True)
    nperpcap = Column(Integer, nullable=True)
    claimed = Column(Integer, index=True, nullable=True)
    claimmode = Column(Integer, nullable=True)
    claimmode_txt = Column(String(256), nullable=True)
    claim2 = Column(Integer, nullable=True)
    claimmode2 = Column(Integer, nullable=True)
    claimmode2_txt = Column(String(256), nullable=True)
    claim3 = Column(Integer, nullable=True)
    claimmode3 = Column(Integer, nullable=True)
    claimmode3_txt = Column(String(256), nullable=True)
    compclaim = Column(Integer, nullable=True)
    weaptype1 = Column(Integer, index=True, nullable=True)
    weaptype1_txt = Column(String(256), index=True, nullable=True)
    weapsubtype1 = Column(Integer, index=True, nullable=True)
    weapsubtype1_txt = Column(String(256), nullable=True)
    weaptype2 = Column(Integer, nullable=True)
    weaptype2_txt = Column(String(256), nullable=True)
    weapsubtype2 = Column(Integer, nullable=True)
    weapsubtype2_txt = Column(String(256), nullable=True)
    weaptype3 = Column(Integer, nullable=True)
    weaptype3_txt = Column(String(256), nullable=True)
    weapsubtype3 = Column(Integer, nullable=True)
    weapsubtype3_txt = Column(String(256), nullable=True)
    weaptype4 = Column(Integer, nullable=True)
    weaptype4_txt = Column(String(256), nullable=True)
    weapsubtype4 = Column(Integer, nullable=True)
    weapsubtype4_txt = Column(String(256), nullable=True)
    weapdetail = Column(Text, nullable=True)
    nkill = Column(Float, index=True, nullable=True)
    nkillus = Column(Float, nullable=True)
    nkillter = Column(Float, nullable=True)
    nwound = Column(Float, index=True, nullable=True)
    nwoundus = Column(Float, nullable=True)
    nwoundte = Column(Float, nullable=True)
    property = Column(Integer, index=True, nullable=True)
    propextent = Column(Integer, nullable=True)
    propextent_txt = Column(String(256), nullable=True)
    propvalue = Column(Float, nullable=True)
    propcomment = Column(Text, nullable=True)
    ishostkid = Column(Integer, index=True, nullable=True)
    nhostkid = Column(Integer, nullable=True)
    nhostkidus = Column(Integer, nullable=True)
    nhours = Column(Integer, nullable=True)
    ndays = Column(Integer, nullable=True)
    divert = Column(String(256), nullable=True)
    kidhijcountry = Column(String(256), nullable=True)
    ransom = Column(Integer, index=True, nullable=True)
    ransomamt = Column(Float, nullable=True)
    ransomamtus = Column(Float, nullable=True)
    ransompaid = Column(Float, nullable=True)
    ransompaidus = Column(Float, nullable=True)
    ransomnote = Column(Text, nullable=True)
    hostkidoutcome = Column(Integer, index=True, nullable=True)
    hostkidoutcome_txt = Column(String(256), nullable=True)
    nreleased = Column(Integer, nullable=True)
    addnotes = Column(Text, nullable=True)
    scite1 = Column(Text, nullable=True)
    scite2 = Column(Text, nullable=True)
    scite3 = Column(Text, nullable=True)
    dbsource = Column(String(256), index=True, nullable=True)
    INT_LOG = Column(Integer, index=True, nullable=True)
    INT_IDEO = Column(Integer, index=True, nullable=True)
    INT_MISC = Column(Integer, index=True, nullable=True)
    INT_ANY = Column(Integer, index=True, nullable=True)
    related = Column(Text, nullable=True)

