from sqlalchemy import Column, Integer, String, ForeignKey, BigInteger
from config.database import Base

class Perpetrator(Base):
    __tablename__ = "perpetrator"

    perpetrator_id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    eventid = Column(BigInteger, ForeignKey("case.eventid"), index=True)
    iyear = Column(Integer, nullable=True, index=True)
    imonth = Column(Integer, nullable=True, index=True)
    iday = Column(Integer, nullable=True, index=True)
    country = Column(Integer, nullable=True, index=True)
    country_txt = Column(String(256), nullable=True, index=True)
    region = Column(Integer, nullable=True, index=True)
    region_txt = Column(String(256), nullable=True, index=True)
    provstate = Column(String(256), nullable=True, index=True)
    city = Column(String(256), nullable=True, index=True)
    gname = Column(String(256), index=True, nullable=True)
    gsubname = Column(String(256), nullable=True)
    gname2 = Column(String(256), nullable=True)
    gsubname2 = Column(String(256), nullable=True)
    gname3 = Column(String(256), nullable=True)
    gsubname3 = Column(String(256), nullable=True)
    guncertain1 = Column(Integer, nullable=True)
    guncertain2 = Column(Integer, nullable=True)
    guncertain3 = Column(Integer, nullable=True)
    individual = Column(Integer, index=True, nullable=True)
    nperps = Column(Integer, nullable=True)
    nperpcap = Column(Integer, nullable=True)
    claimed = Column(Integer, index=True, nullable=True)
    claimmode = Column(Integer, nullable=True)
    claimmode_txt = Column(String(256), nullable=True)
    claim2 = Column(Integer, nullable=True)
    claimmode2 = Column(Integer, nullable=True)
    claimmode2_txt = Column(String(256), nullable=True)
    claim3 = Column(Integer, nullable=True)
    claimmode3 = Column(Integer, nullable=True)
    claimmode3_txt = Column(String(256), nullable=True)
    compclaim = Column(Integer, nullable=True)